[[constraint]]
  branch = "master"
  name = "github.com/andrew-d/go-termutil"

[[constraint]]
  branch = "master"
  name = "github.com/client9/xson"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "2.2.6"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
